src/com/verdin/jsf/bean/DashboardView.java
package com.verdin.jsf.bean;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.primefaces.event.CloseEvent;
import org.primefaces.event.DashboardReorderEvent;
import org.primefaces.event.ToggleEvent;
import org.primefaces.model.DashboardColumn;
import org.primefaces.model.DashboardModel;
import org.primefaces.model.DefaultDashboardColumn;
import org.primefaces.model.DefaultDashboardModel;

import javax.annotation.PostConstruct;

@ManagedBean
@ViewScoped
public class DashboardView implements Serializable {
     
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DashboardModel model;
     
    @PostConstruct
    public void init() {
        model = new DefaultDashboardModel();
        DashboardColumn column1 = new DefaultDashboardColumn();
        DashboardColumn column2 = new DefaultDashboardColumn();
        DashboardColumn column3 = new DefaultDashboardColumn();
        DashboardColumn column4 = new DefaultDashboardColumn();
         
        column1.addWidget("memoryUsage");
        column1.addWidget("clusterLoad");
        column1.addWidget("NameNodeGCcount");
        column1.addWidget("NameNodeHostLoad");
        column1.addWidget("UnderReplicatedBlocks");
         
        column2.addWidget("networkUsage");
        column2.addWidget("HDFSDiskUsage");
        column2.addWidget("NameNodeGCtime");
        column2.addWidget("NameNodeRPC");
        column2.addWidget("HDFSSpaceUtilization");
        column2.addWidget("hbaseMasterHeap");        
         
        column3.addWidget("nameNodeHeap");
        column3.addWidget("nameNodeCPUWIO");
        column3.addWidget("NNConnectionLoad");
        column3.addWidget("Faileddiskvolumes");
        column3.addWidget("Add");
        
        column4.addWidget("CPUUsage");
        column4.addWidget("resourceManageHeap");
        column4.addWidget("NameNodeHeap");
        column4.addWidget("BlocksWithCorruptedReplicas");
 
        model.addColumn(column1);
        model.addColumn(column2);
        model.addColumn(column3);
        model.addColumn(column4);
    }
     
    public void handleReorder(DashboardReorderEvent event) {
        FacesMessage message = new FacesMessage();
        message.setSeverity(FacesMessage.SEVERITY_INFO);
        message.setSummary("Reordered: " + event.getWidgetId());
        message.setDetail("Item index: " + event.getItemIndex() + ", Column index: " + event.getColumnIndex() + ", Sender index: " + event.getSenderColumnIndex());
         
        addMessage(message);
    }
     
    public void handleClose(CloseEvent event) {
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Panel Closed", "Closed panel id:'" + event.getComponent().getId() + "'");
         
        addMessage(message);
    }
     
    public void handleToggle(ToggleEvent event) {
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, event.getComponent().getId() + " toggled", "Status:" + event.getVisibility().name());
         
        addMessage(message);
    }
     
    private void addMessage(FacesMessage message) {
        FacesContext.getCurrentInstance().addMessage(null, message);
    }
     
    public DashboardModel getModel() {
        return model;
    }
}

src/com/verdin/jsf/bean/HbaseView.java
package com.verdin.jsf.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.jboss.logging.Logger;

import com.verdin.jsf.model.Arraylist;
import com.verdin.jsf.model.Configuration;
import com.verdin.jsf.model.Item;
import com.verdin.jsf.model.POJOConfigurationResult;

@Named
@ViewScoped
public class HbaseView implements Serializable {
	
	static final long serialVersionUID = 1237l;
	
	static Logger logger = Logger.getLogger(HbaseView.class);
	
	POJOConfigurationResult _json_as_pojo;
	List<Item> items;
	
	static String DEFAULT_USER = "admin";
	static String DEFAULT_PASS = "admin";
	static String CLUSTER = "YAVA30";// "H2SO4";
	static String HOSTNAME = "192.168.3.132";//192.168.3.132  192.168.3.221 192.168.3.164
	
	  // 		AMBARI_INFRA_SOLR, 		AMBARI_METRIC  	ATLAS  	HIVE  KAFKA  	MAPREDUCE2
	  //       	PIG  RANGER   SQOOP  YARN, ZOOKEEPER, OOZIE	

	static String DEFAULT_SERVICE = "HBASE";
	
	Item _current_item ;
	List<Configuration> _current_configurations;
	Configuration config;
	
		
	@PostConstruct
	public  void init() throws Exception {
		
		
		AmbariRestClient _client  =  new AmbariRestClient(HOSTNAME, CLUSTER);
		  
		 String json =  _client.ambari_configurtion_rest_client (DEFAULT_SERVICE);
		  
		 _json_as_pojo = AmbariConfigurationUtil.json2pojo( json);
	
		 items = _json_as_pojo.getItems();    	
		 
		 System.out.println("items = "+ items.size());
		 
		 Item _current_item = items.stream()
    			 .filter(item -> item.getIsCurrent())
    			 .findAny()
    			 .orElse(null);
		 
		 _current_configurations = _current_item.getConfigurations();
		 
		 System.out.println("_current_configurations = "+ _current_configurations.size());
		 
		 config = getCurrentConfigurationByType("hbase-site");
		 		 		
	}
	
	public String   getType() {
	   	
	   	   return config.getType();
	    	   
		}
	
	public String   getTag() {
	   	
	   	   return config.getTag();
	    	   
		}
	
	public Integer   getVersion() {
	   	
	   	   return config.getVersion();
	    	   
		}
	
	public String   getClusterName() {
	   	
	   	   return config.getConfig().getClusterName();
	    	   
		}
	public String   getStackId() {
		
	   	   return config.getConfig().getStackId();
	    	   
		}
	
	public Map<String, Object >  getProperties(String type) {
		
			// String _type = "\"" + type +"\"";
		
		       Configuration cfg = getCurrentConfigurationByType(type);
		
	   	   return cfg.get_Properties();
	    	   
		}
	
	
	public List<String> getParameters(String type) {
		
		// String _type = "\"" + type +"\"";
	
	       Configuration cfg = getCurrentConfigurationByType(type);
	
   	   return cfg.set_Parameters();
    	   
	}
	
	public Map<String, Object >  getProperties() {
	   	
	   	   return config.get_Properties();
	    	   
		}
	
	public Map<String, Object>    getPropertiesAttributes() {
	   	
	   	   return config.get_PropertiesAttributes();
	    	   
		}
	
   private  Configuration  getCurrentConfigurationByType(String type) {
		
	   String _type = "\"" + type +"\"";
	   
		Configuration c  = _current_configurations.stream()
				 .filter(e -> _type.equalsIgnoreCase(e.getType()))
	   			 .findAny()
	   			 .orElse(null);
			
		
		return c;
	}
	
}

src/com/verdin/jsf/bean/HdfsView.java
package com.verdin.jsf.bean;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.jboss.logging.Logger;

import com.verdin.jsf.model.Configuration;
import com.verdin.jsf.model.Item;
import com.verdin.jsf.model.POJOConfigurationResult;

@Named
@ViewScoped
public class HdfsView implements Serializable {
	
	static final long serialVersionUID = 1237l;
	
	static Logger logger = Logger.getLogger(HdfsView.class);
	
	POJOConfigurationResult _json_as_pojo;
	List<Item> items;
	
	static String DEFAULT_USER = "admin";
	static String DEFAULT_PASS = "admin";
	static String CLUSTER = "YAVA30";// "H2SO4";
	static String HOSTNAME = "192.168.3.132";//192.168.3.132  192.168.3.221 192.168.3.164
	
	  // 		AMBARI_INFRA_SOLR, 		AMBARI_METRIC  	ATLAS  	HIVE  KAFKA  	MAPREDUCE2
	  //       	PIG  RANGER   SQOOP  YARN, ZOOKEEPER, OOZIE	

	static String DEFAULT_SERVICE = "HDFS";
	
	Item _current_item ;
	List<Configuration> _current_configurations;
	Configuration config;
		
	@PostConstruct
	public  void init() throws Exception {
		
		
		AmbariRestClient _client  =  new AmbariRestClient(HOSTNAME, CLUSTER);
		  
		 String json =  _client.ambari_configurtion_rest_client (DEFAULT_SERVICE);
		  
		 _json_as_pojo = AmbariConfigurationUtil.json2pojo( json);
	
		 items = _json_as_pojo.getItems();    	
		 
		 System.out.println("items = "+ items.size());
		 
		 Item _current_item = items.stream()
    			 .filter(item -> item.getIsCurrent())
    			 .findAny()
    			 .orElse(null);
		 
		 _current_configurations = _current_item.getConfigurations();
		 
		 System.out.println("_current_configurations = "+ _current_configurations.size());
		 
		 config = getCurrentConfigurationByType("hdfs-site");
		 		 		
	}
	
	public String   getType() {
	   	
	   	   return config.getType();
	    	   
		}
	
	public String   getTag() {
	   	
	   	   return config.getTag();
	    	   
		}
	
	public Integer   getVersion() {
	   	
	   	   return config.getVersion();
	    	   
		}
	
	public String   getClusterName() {
	   	
	   	   return config.getConfig().getClusterName();
	    	   
		}
	public String   getStackId() {
		
	   	   return config.getConfig().getStackId();
	    	   
		}
	
	public Map<String, Object >  getProperties(String type) {
		
			// String _type = "\"" + type +"\"";
		
		       Configuration cfg = getCurrentConfigurationByType(type);
		
	   	   return cfg.get_Properties();
	    	   
		}
	
	public Map<String, Object >  getProperties() {
	   	
	   	   return config.get_Properties();
	    	   
		}
	
	public Map<String, Object>    getPropertiesAttributes() {
	   	
	   	   return config.get_PropertiesAttributes();
	    	   
		}
	
   private  Configuration  getCurrentConfigurationByType(String type) {
		
	   String _type = "\"" + type +"\"";
	   
		Configuration c  = _current_configurations.stream()
				 .filter(e -> _type.equalsIgnoreCase(e.getType()))
	   			 .findAny()
	   			 .orElse(null);
			
		
		return c;
	}
	
}

src/com/verdin/jsf/bean/MapreduceView.java
package com.verdin.jsf.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.jboss.logging.Logger;


import com.verdin.jsf.model.Configuration;
import com.verdin.jsf.model.Item;
import com.verdin.jsf.model.POJOConfigurationResult;
import com.verdin.jsf.model.Param;


@Named
@ViewScoped
public class MapreduceView implements Serializable {
	
	static final long serialVersionUID = 1237l;
	
	static Logger logger = Logger.getLogger(MapreduceView.class);
	
	POJOConfigurationResult _json_as_pojo;
	List<Item> items;
	
	static String DEFAULT_USER = "admin";
	static String DEFAULT_PASS = "admin";
	static String CLUSTER = "YAVA30";// "H2SO4";
	static String HOSTNAME = "192.168.3.132";//192.168.3.132  192.168.3.221 192.168.3.164
	
	  // 		AMBARI_INFRA_SOLR, 		AMBARI_METRIC  	ATLAS  	HIVE  KAFKA  	MAPREDUCE2
	  //       	PIG  RANGER   SQOOP  YARN, ZOOKEEPER, OOZIE	

	static String DEFAULT_SERVICE = "MAPREDUCE2";
	
	Item _current_item ;
	List<Configuration> _current_configurations;
	Configuration config;
	List<Param> mapred_env = new ArrayList<Param>();
	 
		
	@PostConstruct
	public  void init() throws Exception {
		
		
		AmbariRestClient _client  =  new AmbariRestClient(HOSTNAME, CLUSTER);
		  
		 String json =  _client.ambari_configurtion_rest_client (DEFAULT_SERVICE);
		  
		 _json_as_pojo = AmbariConfigurationUtil.json2pojo( json);
	
		 items = _json_as_pojo.getItems();    	
		 
		 System.out.println("items = "+ items.size());
		 
		 Item _current_item = items.stream()
    			 .filter(item -> item.getIsCurrent())
    			 .findAny()
    			 .orElse(null);
		 
		 _current_configurations = _current_item.getConfigurations();
		 
		 System.out.println("_current_configurations = "+ _current_configurations.size());
		 
		 config = getCurrentConfigurationByType("mapred-site");				 
		 
		 for (Map.Entry<String,Object> entry : getProperties("mapred-env").entrySet()) {
	            //System.out.println("Key = " + entry.getKey() + 
	              //               ", Value = " + entry.getValue()); 
			 Param p = new Param(entry.getKey(),entry.getValue().toString()) ;
			 mapred_env.add(p);
		 } 
	}
	
	public String   getType() {	   	
	   	   return config.getType();	    	   
		}
	
	public String   getTag() {	   	
	   	   return config.getTag();	    	   
		}
	
	public Integer   getVersion() {	   	
	   	   return config.getVersion();	    	   
		}
	
	public String   getClusterName() {	   	
	   	   return config.getConfig().getClusterName();    	   
		}
	
	public String   getStackId() {		
	   	   return config.getConfig().getStackId();	    	   
		}
	
	public List<Param> getMapredParam() {
		return mapred_env;
	}
	
	public void setMapredParam(List<Param> q) {
		logger.info("berhasil");
	}
	
	public void submitAction() {
		   	
			logger.info("submit() ... invoked");			
			
			for (Param f: mapred_env) {
				
	    		logger.info("submitAction() ... "+ f.getKey() +" : "+  f.getValue());
	    		
	    		 getProperties("mapred-env").put(f.getKey(), f.getValue());
				}
	    	}	
	
	public Map<String, Object >  getProperties(String type) {		
			// String _type = "\"" + type +"\"";		
		       //Configuration cfg = getCurrentConfigurationByType(type);
		
	   	   return getCurrentConfigurationByType(type).get_Properties();	    	   
		}
	
	public Map<String, Object >  getProperties() {	   	
	   	   return config.get_Properties();	    	   
		}
	
	public Map<String, Object>    getPropertiesAttributes() {	   	
	   	   return config.get_PropertiesAttributes();	    	   
		}	
	
    private  Configuration  getCurrentConfigurationByType(String type) {
		
	   String _type = "\"" + type +"\"";
	   
		Configuration c  = _current_configurations.stream()
				 .filter(e -> _type.equalsIgnoreCase(e.getType()))
	   			 .findAny()
	   			 .orElse(null);
					
		return c;
	}	
}

src/com/verdin/jsf/bean/PigView.java
package com.verdin.jsf.bean;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.jboss.logging.Logger;

import com.verdin.jsf.model.Configuration;
import com.verdin.jsf.model.Item;
import com.verdin.jsf.model.POJOConfigurationResult;

@Named
@ViewScoped
public class PigView implements Serializable {
	
	static final long serialVersionUID = 1237l;
	
	static Logger logger = Logger.getLogger(PigView.class);
	
	POJOConfigurationResult _json_as_pojo;
	List<Item> items;
	
	static String DEFAULT_USER = "admin";
	static String DEFAULT_PASS = "admin";
	static String CLUSTER = "YAVA30";// "H2SO4";
	static String HOSTNAME = "192.168.3.132";//192.168.3.132  192.168.3.221 192.168.3.164
	
	  // 		AMBARI_INFRA_SOLR, 		AMBARI_METRIC  	ATLAS  	HIVE  KAFKA  	MAPREDUCE2
	  //       	PIG  RANGER   SQOOP  YARN, ZOOKEEPER, OOZIE	

	static String DEFAULT_SERVICE = "PIG";
	
	Item _current_item ;
	List<Configuration> _current_configurations;
	Configuration config;
		
	@PostConstruct
	public  void init() throws Exception {
		
		
		AmbariRestClient _client  =  new AmbariRestClient(HOSTNAME, CLUSTER);
		  
		 String json =  _client.ambari_configurtion_rest_client (DEFAULT_SERVICE);
		  
		 _json_as_pojo = AmbariConfigurationUtil.json2pojo( json);
	
		 items = _json_as_pojo.getItems();    	
		 
		 System.out.println("items = "+ items.size());
		 
		 Item _current_item = items.stream()
    			 .filter(item -> item.getIsCurrent())
    			 .findAny()
    			 .orElse(null);
		 
		 _current_configurations = _current_item.getConfigurations();
		 
		 System.out.println("_current_configurations = "+ _current_configurations.size());
		 
		 config = getCurrentConfigurationByType("pig-site");
		 		 		
	}
	
	public String   getType() {
	   	
	   	   return config.getType();
	    	   
		}
	
	public String   getTag() {
	   	
	   	   return config.getTag();
	    	   
		}
	
	public Integer   getVersion() {
	   	
	   	   return config.getVersion();
	    	   
		}
	
	public String   getClusterName() {
	   	
	   	   return config.getConfig().getClusterName();
	    	   
		}
	public String   getStackId() {
		
	   	   return config.getConfig().getStackId();
	    	   
		}
	
	public Map<String, Object >  getProperties(String type) {
		
			// String _type = "\"" + type +"\"";
		
		       Configuration cfg = getCurrentConfigurationByType(type);
		
	   	   return cfg.get_Properties();
	    	   
		}
	
	public Map<String, Object >  getProperties() {
	   	
	   	   return config.get_Properties();
	    	   
		}
	
	public Map<String, Object>    getPropertiesAttributes() {
	   	
	   	   return config.get_PropertiesAttributes();
	    	   
		}
	
   private  Configuration  getCurrentConfigurationByType(String type) {
		
	   String _type = "\"" + type +"\"";
	   
		Configuration c  = _current_configurations.stream()
				 .filter(e -> _type.equalsIgnoreCase(e.getType()))
	   			 .findAny()
	   			 .orElse(null);
			
		
		return c;
	}
	
}

WebContent/sections/includes/HdfsView.xhtml
<ui:composition
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:p="http://primefaces.org/ui"
        xmlns:pe="http://primefaces.org/ui/extensions">
<!-- EXAMPLE-SOURCE-START -->

<h:form >
	<p:growl id="message"></p:growl>
	
	<p:tabView activeIndex="#{tabViewManagedBean.index}">
	
		<p:tab title="hdfs-site">
		
		<h:panelGrid columns="2" cellpadding="5">
		    <p:outputLabel value="Type: " />
		    <p:outputLabel value="#{hdfsView.type}"></p:outputLabel>
		    
		    <p:outputLabel value="clusterName: " />
		    <p:outputLabel value="#{hdfsView.clusterName}"></p:outputLabel>
		    
		    <p:outputLabel value="stackId: " />
			<p:outputLabel value="#{hdfsView.stackId}"></p:outputLabel>
			
			<p:outputLabel value="version: " />
			<p:outputLabel value="#{hdfsView.version}"></p:outputLabel>
			
			<p:outputLabel value="Tag: " />
			<p:outputLabel value="#{hdfsView.tag}"></p:outputLabel>
			
			</h:panelGrid>
			
			<p:dataTable  var="productEntry"  value="#{hdfsView.properties}">
			   <p:column>
			      <h:outputText value="#{productEntry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{productEntry.value}" />
			   </p:column>
			</p:dataTable>
			
			
		</p:tab>
	
	
	
		<p:tab title="hadoop-env">
		
		
			<p:dataTable  var="entry"  value="#{hdfsView.getProperties('hadoop-env')}">
			   <p:column>
			      <h:outputText value="#{entry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{entry.value}" />
			   </p:column>
			</p:dataTable>
		
		</p:tab>
		
		<p:tab title="hadoop-metrics2.properties">
			<p:dataTable  var="entry"  value="#{hdfsView.getProperties('hadoop-metrics2.properties')}">
			   <p:column>
			      <h:outputText value="#{entry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{entry.value}" />
			   </p:column>
			</p:dataTable>
 
		</p:tab>
		
		<p:tab title="hadoop-policy">
			<p:dataTable  var="entry"  value="#{hdfsView.getProperties('hadoop-policy')}">
			   <p:column>
			      <h:outputText value="#{entry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{entry.value}" />
			   </p:column>
			</p:dataTable>		
		</p:tab>
		
		<p:tab title="hdfs-log4j">
			<p:dataTable  var="entry"  value="#{hdfsView.getProperties('hdfs-log4j')}">
			   <p:column>
			      <h:outputText value="#{entry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{entry.value}" />
			   </p:column>
			</p:dataTable>		
		</p:tab>
		
	  <p:tab title="ranger-hdfs-plugin-properties">
		
			<p:dataTable  var="entry"  value="#{hdfsView.getProperties('ranger-hdfs-plugin-properties')}">
			   <p:column>
			      <h:outputText value="#{entry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{entry.value}" />
			   </p:column>
			</p:dataTable>
			
		</p:tab>
		<p:tab title="ranger-hdfs-policymgr-ssl">
			<p:dataTable  var="entry"  value="#{hdfsView.getProperties('ranger-hdfs-policymgr-ssl')}">
			   <p:column>
			      <h:outputText value="#{entry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{entry.value}" />
			   </p:column>
			</p:dataTable>		
		</p:tab>
		
		<p:tab title="ssl-client">
			<p:dataTable  var="entry"  value="#{hdfsView.getProperties('ssl-client')}">
			   <p:column>
			      <h:outputText value="#{entry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{entry.value}" />
			   </p:column>
			</p:dataTable>		
		</p:tab>
		
		<p:tab title="ssl-server">
			<p:dataTable  var="entry"  value="#{hdfsView.getProperties('ssl-server')}">
			   <p:column>
			      <h:outputText value="#{entry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{entry.value}" />
			   </p:column>
			</p:dataTable>		
		</p:tab>
		
		<p:tab title="viewfs-mount-table">
			<p:dataTable  var="entry"  value="#{hdfsView.getProperties('viewfs-mount-table')}">
			   <p:column>
			      <h:outputText value="#{entry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{entry.value}" />
			   </p:column>
			</p:dataTable>		
		</p:tab>
		
		<p:tab title="ranger-hdfs-audit">
			<p:dataTable  var="entry"  value="#{hdfsView.getProperties('ranger-hdfs-audit')}">
			   <p:column>
			      <h:outputText value="#{entry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{entry.value}" />
			   </p:column>
			</p:dataTable>		
		</p:tab>
		
		<p:tab title="ranger-hdfs-security">
			<p:dataTable  var="entry"  value="#{hdfsView.getProperties('ranger-hdfs-security')}">
			   <p:column>
			      <h:outputText value="#{entry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{entry.value}" />
			   </p:column>
			</p:dataTable>		
		</p:tab>
		
		<p:tab title="core-site">
			<p:dataTable  var="entry"  value="#{hdfsView.getProperties('core-site')}">
			   <p:column>
			      <h:outputText value="#{entry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{entry.value}" />
			   </p:column>
			</p:dataTable>		
		</p:tab>
		
		<p:tab title="hdfs-site">
			<p:dataTable  var="entry"  value="#{hdfsView.getProperties('hdfs-site')}">
			   <p:column>
			      <h:outputText value="#{entry.key}" />
			   </p:column>
			   <p:column>
			       <h:outputText value="#{entry.value}" />
			   </p:column>
			</p:dataTable>		
		</p:tab>
	
	</p:tabView>
</h:form>    
    
</ui:composition>

WebContent/sections/includes/sqoopView.xhtml
<ui:composition xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions">
	<!-- EXAMPLE-SOURCE-START -->

	<h:form>
		<p:growl id="message"></p:growl>

		<p:tabView activeIndex="#{tabViewManagedBean.index}">

			<p:tab title="SUMMARY">

				<h3>SUMMARY</h3>
				<p:breadCrumb style="font-size:10pt">
					<p:menuitem value="Breadcrumb" />
					<p:menuitem value="Services" />
					<p:menuitem value="Sqoop" />
					<p:menuitem value="Summary" />
				</p:breadCrumb>
				<div class="ui-g">
					<div class="ui-g-12 ui-md-2">Component</div>
					<div class="ui-g-12 ui-md-10 ui-g-nopad">
						<div class="ui-g-12 ui-g-nopad">
							<div class="ui-g">
								<div class="ui-g-12 ui-md-4">
									<div>
										<p:outputLabel value="3 Installed"></p:outputLabel>
									</div>
									<div>
										<p:outputLabel value="Sqoop Clients"></p:outputLabel>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</p:tab>
			<p:tab title="CONFIGS">
				<p:breadCrumb style="font-size:10pt">
					<p:menuitem value="Breadcrumb" />
					<p:menuitem value="Services" />
					<p:menuitem value="Sqoop" />
					<p:menuitem value="Configs" />
				</p:breadCrumb>
				<p:accordionPanel>

					<p:tab title="sqoop-env">


						<p:dataTable var="entry"
							value="#{sqoopView.getProperties('sqoop-env')}">
							<p:column>
								<h:outputText value="#{entry.key}" />
							</p:column>
							<p:column>
								<h:outputText value="#{entry.value}" />
							</p:column>
						</p:dataTable>

					</p:tab>


					<p:tab title="sqoop-site">


						<p:dataTable var="entry"
							value="#{sqoopView.getProperties('sqoop-site')}">
							<p:column>
								<h:outputText value="#{entry.key}" />
							</p:column>
							<p:column>
								<h:outputText value="#{entry.value}" />
							</p:column>
						</p:dataTable>

					</p:tab>
					
					<p:tab title="sqoop-site">


						<p:dataTable var="entry"
							value="#{sqoopView.getProperties('sqoop-atlas-application.properties')}">
							<p:column>
								<h:outputText value="#{entry.key}" />
							</p:column>
							<p:column>
								<h:outputText value="#{entry.value}" />
							</p:column>
						</p:dataTable>

					</p:tab>

				</p:accordionPanel>
			</p:tab>

		</p:tabView>
	</h:form>

</ui:composition>